Works on subdomains on own server.
Krystofee/gitlab-unresolved-threads pull request #4
Opened 2020-06-22 15:52 UTC by commentatorboy

Hi! 
I love this extension. Thank you very much!
I have although a request.
It would be nice if you could merge this and push it to the web store.

I have a custom subdomain called like: gitlab.random.com and this extension would not work on those.

Therefore I made some adjustments to it, so that it works on all types of domains now.
It does not have to be gitlab.com it can also be on self-hosted pages. like gitlab.testing.uk

If you have any question please write them :D

2020-06-22 21:41 UTC, Krystofee requested changes
Wow! Thank you using my extension and for the contribution.

2020-06-22 21:41 UTC, Krystofee commented on enhance-merge-requests.js
> +  /^https:\/\/gitlab\.*.*\/.*\/merge_requests\/?(\?.*)?$/.test(
Then I think this could be simplified to

```suggestion
  /^https:\/\/gitlab\.*.*\/merge_requests\/?(\?.*)?$/.test(
```

don't you think?

2020-06-22 21:41 UTC, Krystofee commented on merge-request-checklist.js
> +  /^https:\/\/gitlab\.*.*\/.*\/merge_requests\/?(\?.*)?$/.test(
```suggestion
  /^https:\/\/gitlab\.*.*\/merge_requests\/?(\?.*)?$/.test(
```

The same for this one.

2020-06-22 21:43 UTC, Krystofee commented
Sure I'll update the chrome extension at the web store ASAP after we merge this. But keep in mind this process takes about a week, because of some review at the side of google.

2020-06-22 21:45 UTC, Krystofee approved these changes

2020-06-22 21:46 UTC, merged

2020-06-22 21:50 UTC, Krystofee commented
I've just submitted it to the process of review 🙂

2020-06-23 17:32 UTC, commentatorboy commented
Great to hear! And thank you taking it into consideration!